### ISSUE TITLE
Could not find a version that satisfies the requirement keitaropy

### ISSUE THREAD

**Issue by yaro-137** [Infvmous/keitaropy#1]
Facing an error while trying to install the package:
`
pip3 install keitaropy
ERROR: Could not find a version that satisfies the requirement keitaropy
ERROR: No matching distribution found for keitaropy
`
Seems like keitaropy package builded for some specific version of Python.

**Comment by Infvmous** [comment]
What version of python do you have?

**Comment by ysomad** [comment]
> Facing an error while trying to install the package:
> `pip3 install keitaropy ERROR: Could not find a version that satisfies the requirement keitaropy ERROR: No matching distribution found for keitaropy`
> Seems like keitaropy package builded for some specific version of Python.

What version of python do you have?

**Comment by ysomad** [comment]
keitaropy no longer supported, working on it's refactoring in different branch. Will merge just after I finish main functionality and tests.
